apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 3  # Change this as needed
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: frawatson/todo-app:latest  # Replace <CONTAINER_REGISTRY> with your registry details
          imagePullPolicy: Always
          ports:
            - containerPort: 80